services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    command: >
      bash -c "apt-get update &&
               apt-get install -y docker.io &&""
    ports:
      - "8080:8080"   # Jenkins UI
      - "50000:50000" # inbound agents (optional)
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # let Jenkins talk to Docker on the host
    restart: unless-stopped
