services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root

    ports:
      - "8080:8080"   # Jenkins UI
      - "50000:50000" # inbound agents (optional)
      - "5000:5000"   # ynet app
      - "9090:9090"   # prometheus
      - "3000:3000"   # grafana
      - "5001:5001"   # cadvisor
      - "8082:8082"   # node-exporter
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # let Jenkins talk to Docker on the host
    restart: unless-stopped
